id: I22A835F7
ocr_import_info:
  timestamp: '2023-09-26T07:44:33.629847+00:00'
  batch_id: batch-70b4
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-26 10:34:29.370051+00:00
last_modified: 2023-09-26 10:34:29.370056+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG02533
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG02533
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་ཆོས་ཡིད་བཞིན་གྱི་ནོར་བུ་ཐར་པ་རིན་པོ་ཆེའི་རྒྱན།
  languages:
  - bo
  author: སྒམ་པོ་པ་བསོད་ནམས་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.936504290033494
  ocr_word_median_confidence_index: 0.989646425
bases:
  I00KG03136:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03136
      total_pages: 810
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03136.txt
    statistics:
      ocr_word_median_confidence_index: 0.989646425
      ocr_word_mean_confidence_index: 0.936504290033494
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
